context:
  version: 1.2.0

package:
  name: "mojo_csv"
  version: ${{ version }}

source:
  - git: https://github.com/Phelsong/mojo_csv.git
    rev: e642c060a6fad04b1a42727501c386f812b88e8d

build:
  number: 0
  script:
    - mojo package src -o ${{ PREFIX }}/lib/mojo/mojo_csv.mojopkg

requirements:
  host:
    - max >=25.1.0,<26
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test.mojo test.csv

about:
  homepage: https://github.com/Phelsong/mojo_csv
  license: Apache-2.0
  license_file: LICENSE
  summary: Csv parsing library written in pure Mojo
  repository: https://github.com/Phelsong/mojo_csv

extra:
  maintainers:
    - phelsong
  project_name:
    - mojo_csv
