context:
  version: "0.0.1"

package:
  name: "hue"
  version: ${{ version }}

source:
  - git: https://github.com/thatstoasty/hue.git
    rev: 32ff979d86393cf91068ead70e96ce18cd701106

build:
  number: 2
  script:
    - mojo package src/hue -o ${{ PREFIX }}/lib/mojo/hue.mojopkg
requirements:
  host:
    - max

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo
    requirements:
      run:
       - max

about:
  homepage: https://github.com/thatstoasty/hue
  license: MIT
  license_file: LICENSE
  summary: A library for playing with colors in Mojo. https://github.com/thatstoasty/hue
  repository: https://github.com/thatstoasty/hue
