name: Pipeline

on:
  workflow_dispatch:

jobs:
  pipeline:
    name: Start Pipeline
    timeout-minutes: 60
    runs-on: ubuntu-latest

    # We need to make sure that we have actions read access to get the previous artifact
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.31.0
          environments: data

      - name: Download artifact
        run: |
          pixi run download-previous-artifact
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update data
        run: |
          pixi run update-data

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.json
          retention-days: 60
