name: Check Incompatible Packages

on:
  schedule:
    - cron: "0 17 * * *" # 9 AM PST

jobs:
  check-incompatible-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run compatibility check script
        run: pixi run create-pr-incompatible-packages
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Commit changes to failed-compatibility.json
        if: github.ref == 'refs/heads/main'
        run: |
          pixi run commit-changes data/failed-compatibility.json
